# Generated by Django 4.1 on 2022-08-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان غدا')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('image', models.ImageField(null=True, upload_to='image/product')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت : فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='آدرس')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'غدا و نوشیدنی ',
                'verbose_name_plural': 'غدا و نوشیدنی ها',
            },
        ),
    ]
