# Generated by Django 4.1 on 2022-08-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_product_options_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول ', 'verbose_name_plural': 'محصولات '},
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='image/img-categories', verbose_name='عکس_دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default=1, max_length=120, verbose_name='توضیح مختصر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug_address',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس url محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='عنوان محصول'),
        ),
    ]
