# Generated by Django 4.1 on 2022-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_otp_options_alter_otp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(max_length=10),
        ),
    ]
