# Generated by Django 4.1 on 2022-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
