# Generated by Django 4.1 on 2022-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='image/users_profile', verbose_name='عکس کاربری'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(max_length=130, verbose_name='بیوگرافی'),
        ),
    ]
